# Generated by Django 4.1.7 on 2023-02-28 12:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1440, 368],
                upload_to="item_images",
            ),
        ),
    ]
